--CREATE DEPARTMENT TABLE
CREATE TABLE DEPARTMENT(
DEPARTMENT_ID INTEGER PRIMARY KEY,
DEPARTMENT_NAME VARCHAR2(100));
/

--CREATE EMPLOYEE SEQUENCE FOR PRIMARY KEY
CREATE SEQUENCE DEPARTMENTSEQ
    START WITH 1
    INCREMENT BY 1;
/

--CREATE EMPLOYEE TABLE
DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE(
EMPLOYEE_ID INTEGER PRIMARY KEY,
EMP_FIRSTNAME VARCHAR2(50),
EMP_LASTNAME VARCHAR2(50),
DEPARTMENT_ID INTEGER,
SALARY NUMBER(38,4),
EMP_EMAIL VARCHAR2(100),
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
);
/

CREATE SEQUENCE EMPLOYEESEQ
    START WITH 1
    INCREMENT BY 1;
/

--INSERTS INTO DEPARTMENT TABLE
INSERT INTO DEPARTMENT VALUES(DEPARTMENTSEQ.NEXTVAL, 'Trainer'); --department_id = 1
INSERT INTO DEPARTMENT VALUES(DEPARTMENTSEQ.NEXTVAL, 'Human Resources'); --department_id = 2
INSERT INTO DEPARTMENT VALUES(DEPARTMENTSEQ.NEXTVAL, 'Associate'); --department_id = 3

--INSERTS INTO EMPLOYEE TABLE
INSERT INTO EMPLOYEE VALUES(EMPLOYEESEQ.NEXTVAL, 'Dylan', 'Waser', 3, 100000, 'waserdylan@gmail.com');
INSERT INTO EMPLOYEE VALUES(EMPLOYEESEQ.NEXTVAL, 'Emily', 'Higgins', 1, 300000, 'higginsemily@gmail.com');
INSERT INTO EMPLOYEE VALUES(EMPLOYEESEQ.NEXTVAL, 'Matthew', 'Knighten', 1, 301000, 'knightenmatthew@gmail.com');
INSERT INTO EMPLOYEE VALUES(EMPLOYEESEQ.NEXTVAL, 'Matthew', 'Robertson', 3, 101000, 'lavalamp@gmail.com');
INSERT INTO EMPLOYEE VALUES(EMPLOYEESEQ.NEXTVAL, 'John', 'Doe', 2, 125000, 'doejohn@gmail.com');
INSERT INTO EMPLOYEE VALUES(EMPLOYEESEQ.NEXTVAL, 'Jane', 'Doe', 2, 125000, 'doejane@gmail.com');

CREATE OR REPLACE PROCEDURE INSERTEMPLOYEE(THISFIRSTNAME IN VARCHAR2, THISLASTNAME IN VARCHAR2, THISDEPARTMENTID IN INTEGER, THISSALARY IN NUMBER, THISEMAIL IN VARCHAR2)
AS
BEGIN
    INSERT INTO EMPLOYEE VALUES(EMPLOYEESEQ.NEXTVAL, THISFIRSTNAME, THISLASTNAME, THISDEPARTMENTID, THISSALARY, THISEMAIL);
COMMIT;
END;
/

--AVG salary per department
SELECT D.DEPARTMENT_NAME, AVG(E.SALARY)
FROM DEPARTMENT D
RIGHT JOIN EMPLOYEE E
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME
ORDER BY AVG(E.SALARY) DESC;
